#!/bin/bash
API_KEY="re_FdNcsnxT_9ZA3oDGrQjsNcP73GaMw3DSN"
SENT=0
FAILED=0

send_email() {
  local TO="$1"
  local SUBJECT="$2"
  local HTML="$3"
  
  RESPONSE=$(curl -s -X POST https://api.resend.com/emails \
    -H "Authorization: Bearer $API_KEY" \
    -H "Content-Type: application/json" \
    -d "{\"from\":\"Ash from ReCapture <hello@userecapture.com>\",\"to\":\"$TO\",\"reply_to\":\"asherton.c@me.com\",\"subject\":\"$SUBJECT\",\"html\":$(echo "$HTML" | python3 -c 'import sys,json; print(json.dumps(sys.stdin.read()))')}")
  
  if echo "$RESPONSE" | grep -q '"id"'; then
    echo "SENT: $TO — $SUBJECT"
    SENT=$((SENT+1))
  else
    echo "FAILED: $TO — $RESPONSE"
    FAILED=$((FAILED+1))
  fi
  sleep 2
}

MEDSPA_HTML='<div style="font-family: -apple-system, Segoe UI, sans-serif; max-width: 560px; margin: 0 auto; background: #0a0a0a; color: #ccc; padding: 36px 32px; border-radius: 10px;"><div style="margin-bottom: 28px;"><span style="font-size: 18px; font-weight: 700; color: #fff;">Re</span><span style="font-size: 18px; font-weight: 700; color: #ff6b35;">Capture</span></div><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">Hi there,</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">I am Ash — I run a digital marketing consultancy here in the Harwood District in Dallas. I have spent the last 10+ years managing ad campaigns for med spas and high-ticket service businesses, and I kept seeing the same problem everywhere.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">Between 60% and 70% of people who start a contact form on your website never finish it. They type their name, their email, maybe their phone number — then they get distracted and close the tab. Nobody shows you the people in between.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">For med spas, the average client is worth $2,800. If even 5 of those invisible leads had converted last month, that would be $14,000 in revenue your practice never saw.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 24px;">I built ReCapture to fix this. One script tag on your website — takes 60 seconds to install. Every person who starts your form is captured in real time, even if they never hit submit. You see their name, email, phone, and the estimated value of that lead.</p><div style="text-align: center; margin: 28px 0;"><a href="https://www.userecapture.com/test-form" style="display: inline-block; background: #ff6b35; color: #fff; font-weight: 700; padding: 12px 28px; border-radius: 8px; text-decoration: none; font-size: 14px;">See It in Action — Live Demo</a></div><p style="font-size: 14px; line-height: 1.7; color: #888; margin-bottom: 20px;">You can also <a href="https://www.userecapture.com/for-med-spas" style="color: #ff6b35; text-decoration: none;">see how it works for med spas</a> or <a href="https://www.userecapture.com/calculator" style="color: #ff6b35; text-decoration: none;">run a free ROI estimate</a>.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 4px;">Happy to walk you through it.</p><div style="margin-top: 28px; padding-top: 20px; border-top: 1px solid #1e1e1e;"><p style="margin: 0; font-size: 14px; font-weight: 600; color: #fff;">Asherton Chraibi</p><p style="margin: 2px 0 0; font-size: 13px; color: #666;">Founder, ReCapture</p><p style="margin: 2px 0 0; font-size: 13px; color: #666;">Dallas, TX</p><p style="margin: 4px 0 0; font-size: 13px;"><a href="https://www.userecapture.com" style="color: #ff6b35; text-decoration: none;">userecapture.com</a></p></div></div>'

DENTAL_HTML='<div style="font-family: -apple-system, Segoe UI, sans-serif; max-width: 560px; margin: 0 auto; background: #0a0a0a; color: #ccc; padding: 36px 32px; border-radius: 10px;"><div style="margin-bottom: 28px;"><span style="font-size: 18px; font-weight: 700; color: #fff;">Re</span><span style="font-size: 18px; font-weight: 700; color: #ff6b35;">Capture</span></div><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">Hi there,</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">I am Ash — I run a digital marketing consultancy here in the Harwood District in Dallas. I have spent the last 10+ years managing ad campaigns for dental practices and high-ticket service businesses, and I kept seeing the same problem.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">Between 60% and 70% of people who start a patient intake or appointment form never finish it. They type their name, email, maybe their insurance info — then they get distracted and close the tab. Nobody shows you those people.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">For dental practices, a single new patient is worth $1,900 over their lifetime. If even 3 of those invisible leads had booked last month, that is $5,700 your front desk never knew about.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 24px;">I built ReCapture to fix this. One script tag — 60 seconds to install. Every person who starts your form is captured in real time, even if they never submit. You see their name, email, phone, and estimated value.</p><div style="text-align: center; margin: 28px 0;"><a href="https://www.userecapture.com/test-form" style="display: inline-block; background: #ff6b35; color: #fff; font-weight: 700; padding: 12px 28px; border-radius: 8px; text-decoration: none; font-size: 14px;">See It in Action — Live Demo</a></div><p style="font-size: 14px; line-height: 1.7; color: #888; margin-bottom: 20px;">You can also <a href="https://www.userecapture.com/for-dental" style="color: #ff6b35; text-decoration: none;">see how it works for dental</a> or <a href="https://www.userecapture.com/calculator" style="color: #ff6b35; text-decoration: none;">run a free ROI estimate</a>.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 4px;">Happy to walk you through it.</p><div style="margin-top: 28px; padding-top: 20px; border-top: 1px solid #1e1e1e;"><p style="margin: 0; font-size: 14px; font-weight: 600; color: #fff;">Asherton Chraibi</p><p style="margin: 2px 0 0; font-size: 13px; color: #666;">Founder, ReCapture</p><p style="margin: 2px 0 0; font-size: 13px; color: #666;">Dallas, TX</p><p style="margin: 4px 0 0; font-size: 13px;"><a href="https://www.userecapture.com" style="color: #ff6b35; text-decoration: none;">userecapture.com</a></p></div></div>'

PROPERTY_HTML='<div style="font-family: -apple-system, Segoe UI, sans-serif; max-width: 560px; margin: 0 auto; background: #0a0a0a; color: #ccc; padding: 36px 32px; border-radius: 10px;"><div style="margin-bottom: 28px;"><span style="font-size: 18px; font-weight: 700; color: #fff;">Re</span><span style="font-size: 18px; font-weight: 700; color: #ff6b35;">Capture</span></div><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">Hi there,</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">I am Ash — I run a digital marketing consultancy here in the Harwood District in Dallas. I have spent the last 10+ years managing ad campaigns for property management companies and high-ticket service businesses.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">70% of people who start a leasing inquiry or tour request form never finish it. They type their name, the unit they want, maybe their move-in date — then they move on to the next listing. Nobody shows you those people.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">Every abandoned leasing inquiry is a $3,200+ annual lease walking to the next listing. Across your portfolio, that adds up to hundreds of thousands in lost lease revenue per year.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 24px;">I built ReCapture to fix this. One script tag per property site — 60 seconds to install. Every prospect who starts your form is captured in real time. Enterprise dashboard across all your properties.</p><div style="text-align: center; margin: 28px 0;"><a href="https://www.userecapture.com/test-form" style="display: inline-block; background: #ff6b35; color: #fff; font-weight: 700; padding: 12px 28px; border-radius: 8px; text-decoration: none; font-size: 14px;">See It in Action — Live Demo</a></div><p style="font-size: 14px; line-height: 1.7; color: #888; margin-bottom: 20px;">You can also <a href="https://www.userecapture.com/for-property-management" style="color: #ff6b35; text-decoration: none;">see how it works for property management</a> or <a href="https://www.userecapture.com/calculator" style="color: #ff6b35; text-decoration: none;">run a free ROI estimate</a>.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 4px;">Happy to walk you through it.</p><div style="margin-top: 28px; padding-top: 20px; border-top: 1px solid #1e1e1e;"><p style="margin: 0; font-size: 14px; font-weight: 600; color: #fff;">Asherton Chraibi</p><p style="margin: 2px 0 0; font-size: 13px; color: #666;">Founder, ReCapture</p><p style="margin: 2px 0 0; font-size: 13px; color: #666;">Dallas, TX</p><p style="margin: 4px 0 0; font-size: 13px;"><a href="https://www.userecapture.com" style="color: #ff6b35; text-decoration: none;">userecapture.com</a></p></div></div>'

SURGERY_HTML='<div style="font-family: -apple-system, Segoe UI, sans-serif; max-width: 560px; margin: 0 auto; background: #0a0a0a; color: #ccc; padding: 36px 32px; border-radius: 10px;"><div style="margin-bottom: 28px;"><span style="font-size: 18px; font-weight: 700; color: #fff;">Re</span><span style="font-size: 18px; font-weight: 700; color: #ff6b35;">Capture</span></div><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">Hi there,</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">I am Ash — I run a digital marketing consultancy here in the Harwood District in Dallas. I have spent the last 10+ years managing ad campaigns for plastic surgery practices and high-ticket service businesses.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">72% of people who start a consultation form never finish it. They type their name, the procedure they want — then they hesitate and close the tab. Nobody shows you those people.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">The average consultation that converts is worth $6,500. If even 2 of those invisible leads had booked, that is $13,000 in procedures your team never saw.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 24px;">I built ReCapture to fix this. One script tag — 60 seconds to install. Every person who starts your consultation form is captured in real time, even if they never submit.</p><div style="text-align: center; margin: 28px 0;"><a href="https://www.userecapture.com/test-form" style="display: inline-block; background: #ff6b35; color: #fff; font-weight: 700; padding: 12px 28px; border-radius: 8px; text-decoration: none; font-size: 14px;">See It in Action — Live Demo</a></div><p style="font-size: 14px; line-height: 1.7; color: #888; margin-bottom: 20px;">You can also <a href="https://www.userecapture.com/for-plastic-surgery" style="color: #ff6b35; text-decoration: none;">see how it works for plastic surgery</a> or <a href="https://www.userecapture.com/calculator" style="color: #ff6b35; text-decoration: none;">run a free ROI estimate</a>.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 4px;">Happy to walk you through it.</p><div style="margin-top: 28px; padding-top: 20px; border-top: 1px solid #1e1e1e;"><p style="margin: 0; font-size: 14px; font-weight: 600; color: #fff;">Asherton Chraibi</p><p style="margin: 2px 0 0; font-size: 13px; color: #666;">Founder, ReCapture</p><p style="margin: 2px 0 0; font-size: 13px; color: #666;">Dallas, TX</p><p style="margin: 4px 0 0; font-size: 13px;"><a href="https://www.userecapture.com" style="color: #ff6b35; text-decoration: none;">userecapture.com</a></p></div></div>'

AUTO_HTML='<div style="font-family: -apple-system, Segoe UI, sans-serif; max-width: 560px; margin: 0 auto; background: #0a0a0a; color: #ccc; padding: 36px 32px; border-radius: 10px;"><div style="margin-bottom: 28px;"><span style="font-size: 18px; font-weight: 700; color: #fff;">Re</span><span style="font-size: 18px; font-weight: 700; color: #ff6b35;">Capture</span></div><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">Hi there,</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">I am Ash — I run a digital marketing consultancy here in the Harwood District in Dallas. I thought of Earth Motorcars when I came across some data I wanted to share.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">74% of people who start a vehicle inquiry form never finish it. They type their name, the model they want — then they close the tab and move on. Nobody shows you those people.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">Every serious inquiry that slips through is an $8,500+ deal walking to the next lot. If even 1 of those invisible leads had come in last month, it would have more than paid for itself.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 24px;">I built ReCapture to fix this. One script tag — 60 seconds to install. Every buyer who starts your form is captured in real time, even if they never submit.</p><div style="text-align: center; margin: 28px 0;"><a href="https://www.userecapture.com/test-form" style="display: inline-block; background: #ff6b35; color: #fff; font-weight: 700; padding: 12px 28px; border-radius: 8px; text-decoration: none; font-size: 14px;">See It in Action — Live Demo</a></div><p style="font-size: 14px; line-height: 1.7; color: #888; margin-bottom: 20px;">You can also <a href="https://www.userecapture.com/for-luxury-auto" style="color: #ff6b35; text-decoration: none;">see how it works for luxury auto</a> or <a href="https://www.userecapture.com/calculator" style="color: #ff6b35; text-decoration: none;">run a free ROI estimate</a>.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 4px;">Happy to walk you through it.</p><div style="margin-top: 28px; padding-top: 20px; border-top: 1px solid #1e1e1e;"><p style="margin: 0; font-size: 14px; font-weight: 600; color: #fff;">Asherton Chraibi</p><p style="margin: 2px 0 0; font-size: 13px; color: #666;">Founder, ReCapture</p><p style="margin: 2px 0 0; font-size: 13px; color: #666;">Dallas, TX</p><p style="margin: 4px 0 0; font-size: 13px;"><a href="https://www.userecapture.com" style="color: #ff6b35; text-decoration: none;">userecapture.com</a></p></div></div>'

echo "Starting batch — 25 emails"
echo "=========================="

# Med Spas
send_email "info@enlightenmd.com" "67% of your consultation leads are invisible" "$MEDSPA_HTML"
send_email "Hello@Sanjivamedspa.com" "67% of your consultation leads are invisible" "$MEDSPA_HTML"
send_email "info@secretmedspa.com" "67% of your consultation leads are invisible" "$MEDSPA_HTML"
send_email "Info@thescienceofbeautydallas.com" "67% of your consultation leads are invisible" "$MEDSPA_HTML"
send_email "hello@glo30.com" "67% of your consultation leads are invisible" "$MEDSPA_HTML"
send_email "dallas@hiatusspa.com" "67% of your consultation leads are invisible" "$MEDSPA_HTML"
send_email "info@starwoodmedspa.com" "67% of your consultation leads are invisible" "$MEDSPA_HTML"
send_email "info@totalmedsolutions.com" "67% of your consultation leads are invisible" "$MEDSPA_HTML"
send_email "info@bodyloungeparkcities.com" "67% of your consultation leads are invisible" "$MEDSPA_HTML"
send_email "contact@elevatemedicalspa.com" "67% of your consultation leads are invisible" "$MEDSPA_HTML"
send_email "info@omnisculptmd.com" "67% of your consultation leads are invisible" "$MEDSPA_HTML"

# Dental
send_email "luxedental@gmail.com" "67% of your form leads are invisible" "$DENTAL_HTML"
send_email "luxedentalvp@gmail.com" "67% of your form leads are invisible" "$DENTAL_HTML"
send_email "info@mintdentistry.com" "quick question about your patient intake forms" "$DENTAL_HTML"
send_email "info@thrivedentist.com" "quick question about your patient intake forms" "$DENTAL_HTML"
send_email "ccanava@decadental.com" "following up — 200+ locations, one blind spot" "$DENTAL_HTML"
send_email "info@myidealdental.com" "following up — 200+ locations, one blind spot" "$DENTAL_HTML"
send_email "sahmed@decadental.com" "following up — 200+ locations, one blind spot" "$DENTAL_HTML"

# Plastic Surgery
send_email "info@northtexasps.com" "72% of consultations never make it to your team" "$SURGERY_HTML"

# Luxury Auto
send_email "sales@earthmotorcars.com" "thought of Earth Motorcars when I saw this" "$AUTO_HTML"

# Property Management
send_email "contact@billingsleyco.com" "your leasing forms are losing prospects" "$PROPERTY_HTML"
send_email "marketing@anterra.com" "your leasing forms are losing prospects" "$PROPERTY_HTML"
send_email "info@cafcapital.com" "your leasing forms are losing prospects" "$PROPERTY_HTML"
send_email "corporate@lumapm.com" "your leasing forms are losing prospects" "$PROPERTY_HTML"
send_email "info@compassmf.com" "your leasing forms are losing prospects" "$PROPERTY_HTML"

echo "=========================="
echo "Batch complete."
