#!/bin/bash
API_KEY="re_FdNcsnxT_9ZA3oDGrQjsNcP73GaMw3DSN"

send_email() {
  local TO="$1"
  local SUBJECT="$2"
  local HTML="$3"
  
  RESPONSE=$(curl -s -X POST https://api.resend.com/emails \
    -H "Authorization: Bearer $API_KEY" \
    -H "Content-Type: application/json" \
    -d "{\"from\":\"Ash from ReCapture <hello@userecapture.com>\",\"to\":\"$TO\",\"reply_to\":\"asherton.c@me.com\",\"subject\":\"$SUBJECT\",\"html\":$(echo "$HTML" | python3 -c 'import sys,json; print(json.dumps(sys.stdin.read()))')}")
  
  if echo "$RESPONSE" | grep -q '"id"'; then
    echo "SENT: $TO — $SUBJECT"
  else
    echo "FAILED: $TO — $RESPONSE"
  fi
  sleep 2
}

MEDSPA_HTML='<div style="font-family: -apple-system, Segoe UI, sans-serif; max-width: 560px; margin: 0 auto; background: #0a0a0a; color: #ccc; padding: 36px 32px; border-radius: 10px;"><div style="margin-bottom: 28px;"><span style="font-size: 18px; font-weight: 700; color: #fff;">Re</span><span style="font-size: 18px; font-weight: 700; color: #ff6b35;">Capture</span></div><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">Hi there,</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">I am Ash — I run a digital marketing consultancy here in the Harwood District in Dallas. I have spent the last 10+ years working with med spas and high-ticket service businesses, and I kept seeing the same problem everywhere.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">Between 60-70% of people who start a consultation form never finish it. They type their name, email, maybe their phone — then they get distracted and close the tab. Nobody shows you the people in between.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">For med spas, the average client is worth $2,800. If even 5 of those invisible leads converted last month, that is $14,000 your practice never saw.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 24px;">I built ReCapture to fix this. One script tag — 60 seconds to install. Every person who starts your form is captured in real time, even if they never hit submit.</p><div style="text-align: center; margin: 28px 0;"><a href="https://www.userecapture.com/test-form" style="display: inline-block; background: #ff6b35; color: #fff; font-weight: 700; padding: 12px 28px; border-radius: 8px; text-decoration: none; font-size: 14px;">See It in Action</a></div><p style="font-size: 14px; line-height: 1.7; color: #888; margin-bottom: 20px;">You can also <a href="https://www.userecapture.com/for-med-spas" style="color: #ff6b35; text-decoration: none;">see how it works for med spas</a> or <a href="https://www.userecapture.com/calculator" style="color: #ff6b35; text-decoration: none;">run a free ROI estimate</a>.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 4px;">Happy to walk you through it.</p><div style="margin-top: 28px; padding-top: 20px; border-top: 1px solid #1e1e1e;"><p style="margin: 0; font-size: 14px; font-weight: 600; color: #fff;">Asherton Chraibi</p><p style="margin: 2px 0 0; font-size: 13px; color: #666;">Founder, ReCapture</p><p style="margin: 2px 0 0; font-size: 13px; color: #666;">Dallas, TX</p><p style="margin: 4px 0 0; font-size: 13px;"><a href="https://www.userecapture.com" style="color: #ff6b35; text-decoration: none;">userecapture.com</a></p></div></div>'

DENTAL_HTML='<div style="font-family: -apple-system, Segoe UI, sans-serif; max-width: 560px; margin: 0 auto; background: #0a0a0a; color: #ccc; padding: 36px 32px; border-radius: 10px;"><div style="margin-bottom: 28px;"><span style="font-size: 18px; font-weight: 700; color: #fff;">Re</span><span style="font-size: 18px; font-weight: 700; color: #ff6b35;">Capture</span></div><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">Hi there,</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">I am Ash — I run a digital marketing consultancy here in Dallas. I have spent the last 10+ years working with dental practices and high-ticket service businesses.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">65% of people who start a patient intake or appointment form never finish it. They type their name, email, maybe insurance info — then they close the tab. Nobody shows you those people.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">A single new patient is worth $1,900 over their lifetime. Across your locations, that adds up to hundreds of thousands in invisible lost revenue per year.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 24px;">I built ReCapture to fix this. One script tag per site — 60 seconds to install. Every person who starts your form is captured in real time, even if they never submit.</p><div style="text-align: center; margin: 28px 0;"><a href="https://www.userecapture.com/test-form" style="display: inline-block; background: #ff6b35; color: #fff; font-weight: 700; padding: 12px 28px; border-radius: 8px; text-decoration: none; font-size: 14px;">See It in Action</a></div><p style="font-size: 14px; line-height: 1.7; color: #888; margin-bottom: 20px;">You can also <a href="https://www.userecapture.com/for-dental" style="color: #ff6b35; text-decoration: none;">see how it works for dental</a> or <a href="https://www.userecapture.com/calculator" style="color: #ff6b35; text-decoration: none;">run a free ROI estimate</a>.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 4px;">Happy to walk you through it.</p><div style="margin-top: 28px; padding-top: 20px; border-top: 1px solid #1e1e1e;"><p style="margin: 0; font-size: 14px; font-weight: 600; color: #fff;">Asherton Chraibi</p><p style="margin: 2px 0 0; font-size: 13px; color: #666;">Founder, ReCapture</p><p style="margin: 2px 0 0; font-size: 13px; color: #666;">Dallas, TX</p><p style="margin: 4px 0 0; font-size: 13px;"><a href="https://www.userecapture.com" style="color: #ff6b35; text-decoration: none;">userecapture.com</a></p></div></div>'

SURGERY_HTML='<div style="font-family: -apple-system, Segoe UI, sans-serif; max-width: 560px; margin: 0 auto; background: #0a0a0a; color: #ccc; padding: 36px 32px; border-radius: 10px;"><div style="margin-bottom: 28px;"><span style="font-size: 18px; font-weight: 700; color: #fff;">Re</span><span style="font-size: 18px; font-weight: 700; color: #ff6b35;">Capture</span></div><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">Hi there,</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">I am Ash — I run a digital marketing consultancy here in the Harwood District in Dallas. I have spent the last 10+ years working with plastic surgery practices and high-ticket service businesses.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">72% of people who start a consultation form never finish it. They type their name, the procedure they want — then they hesitate and close the tab. Nobody shows you those people.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">The average consultation that converts is worth $6,500. If even 2 of those invisible leads had booked, that is $13,000 in procedures your team never saw.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 24px;">I built ReCapture to fix this. One script tag — 60 seconds to install. Every person who starts your form is captured in real time, even if they never submit.</p><div style="text-align: center; margin: 28px 0;"><a href="https://www.userecapture.com/test-form" style="display: inline-block; background: #ff6b35; color: #fff; font-weight: 700; padding: 12px 28px; border-radius: 8px; text-decoration: none; font-size: 14px;">See It in Action</a></div><p style="font-size: 14px; line-height: 1.7; color: #888; margin-bottom: 20px;">You can also <a href="https://www.userecapture.com/for-plastic-surgery" style="color: #ff6b35; text-decoration: none;">see how it works for plastic surgery</a> or <a href="https://www.userecapture.com/calculator" style="color: #ff6b35; text-decoration: none;">run a free ROI estimate</a>.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 4px;">Happy to walk you through it.</p><div style="margin-top: 28px; padding-top: 20px; border-top: 1px solid #1e1e1e;"><p style="margin: 0; font-size: 14px; font-weight: 600; color: #fff;">Asherton Chraibi</p><p style="margin: 2px 0 0; font-size: 13px; color: #666;">Founder, ReCapture</p><p style="margin: 2px 0 0; font-size: 13px; color: #666;">Dallas, TX</p><p style="margin: 4px 0 0; font-size: 13px;"><a href="https://www.userecapture.com" style="color: #ff6b35; text-decoration: none;">userecapture.com</a></p></div></div>'

AUTO_HTML='<div style="font-family: -apple-system, Segoe UI, sans-serif; max-width: 560px; margin: 0 auto; background: #0a0a0a; color: #ccc; padding: 36px 32px; border-radius: 10px;"><div style="margin-bottom: 28px;"><span style="font-size: 18px; font-weight: 700; color: #fff;">Re</span><span style="font-size: 18px; font-weight: 700; color: #ff6b35;">Capture</span></div><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">Hi there,</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">I am Ash — I run a digital marketing consultancy here in Dallas. I thought of your dealership group when I came across some data I wanted to share.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">74% of people who start a vehicle inquiry form never finish it. They type their name, the model they want — then they close the tab. Nobody shows you those people.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">Every serious inquiry that slips through is an $8,500+ deal walking to the next lot. Across your locations, that adds up fast.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 24px;">I built ReCapture to fix this. One script tag per dealership site — 60 seconds to install. Every buyer who starts your form is captured in real time, even if they never submit.</p><div style="text-align: center; margin: 28px 0;"><a href="https://www.userecapture.com/test-form" style="display: inline-block; background: #ff6b35; color: #fff; font-weight: 700; padding: 12px 28px; border-radius: 8px; text-decoration: none; font-size: 14px;">See It in Action</a></div><p style="font-size: 14px; line-height: 1.7; color: #888; margin-bottom: 20px;">You can also <a href="https://www.userecapture.com/for-luxury-auto" style="color: #ff6b35; text-decoration: none;">see how it works for luxury auto</a> or <a href="https://www.userecapture.com/calculator" style="color: #ff6b35; text-decoration: none;">run a free ROI estimate</a>.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 4px;">Happy to walk you through it.</p><div style="margin-top: 28px; padding-top: 20px; border-top: 1px solid #1e1e1e;"><p style="margin: 0; font-size: 14px; font-weight: 600; color: #fff;">Asherton Chraibi</p><p style="margin: 2px 0 0; font-size: 13px; color: #666;">Founder, ReCapture</p><p style="margin: 2px 0 0; font-size: 13px; color: #666;">Dallas, TX</p><p style="margin: 4px 0 0; font-size: 13px;"><a href="https://www.userecapture.com" style="color: #ff6b35; text-decoration: none;">userecapture.com</a></p></div></div>'

PROPERTY_HTML='<div style="font-family: -apple-system, Segoe UI, sans-serif; max-width: 560px; margin: 0 auto; background: #0a0a0a; color: #ccc; padding: 36px 32px; border-radius: 10px;"><div style="margin-bottom: 28px;"><span style="font-size: 18px; font-weight: 700; color: #fff;">Re</span><span style="font-size: 18px; font-weight: 700; color: #ff6b35;">Capture</span></div><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">Hi there,</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">I am Ash — I run a digital marketing consultancy here in the Harwood District in Dallas. I have spent the last 10+ years working with property management companies and multifamily operators.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">70% of people who start a leasing inquiry or tour request form never finish it. They type their name, the unit they want — then they move on to the next listing. Nobody shows you those people.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 20px;">Every abandoned inquiry is a $3,200+ annual lease walking away. Across your portfolio, that adds up to hundreds of thousands in lost lease revenue per year.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 24px;">I built ReCapture to fix this. One script tag per property site — 60 seconds to install. Enterprise dashboard across all your communities.</p><div style="text-align: center; margin: 28px 0;"><a href="https://www.userecapture.com/test-form" style="display: inline-block; background: #ff6b35; color: #fff; font-weight: 700; padding: 12px 28px; border-radius: 8px; text-decoration: none; font-size: 14px;">See It in Action</a></div><p style="font-size: 14px; line-height: 1.7; color: #888; margin-bottom: 20px;">You can also <a href="https://www.userecapture.com/for-property-management" style="color: #ff6b35; text-decoration: none;">see how it works for property management</a> or <a href="https://www.userecapture.com/calculator" style="color: #ff6b35; text-decoration: none;">run a free ROI estimate</a>.</p><p style="font-size: 15px; line-height: 1.7; color: #bbb; margin-bottom: 4px;">Happy to walk you through it.</p><div style="margin-top: 28px; padding-top: 20px; border-top: 1px solid #1e1e1e;"><p style="margin: 0; font-size: 14px; font-weight: 600; color: #fff;">Asherton Chraibi</p><p style="margin: 2px 0 0; font-size: 13px; color: #666;">Founder, ReCapture</p><p style="margin: 2px 0 0; font-size: 13px; color: #666;">Dallas, TX</p><p style="margin: 4px 0 0; font-size: 13px;"><a href="https://www.userecapture.com" style="color: #ff6b35; text-decoration: none;">userecapture.com</a></p></div></div>'

echo "Starting NEW batch — 23 emails"
echo "================================"

# Med Spas
send_email "contact@renewbeautymedspa.com" "67% of your consultation leads never reach the front desk" "$MEDSPA_HTML"
send_email "info@modernmedicalspa.com" "quick question about your booking forms" "$MEDSPA_HTML"
send_email "info@vivadayspa.com" "67% of your Dallas consultation leads are invisible" "$MEDSPA_HTML"
send_email "brandy@dalluremedspa.com" "67% of your consultation leads are invisible" "$MEDSPA_HTML"
send_email "hiddenbeauty@rejuvemedspa.com" "67% of your consultation leads are invisible" "$MEDSPA_HTML"
send_email "info@suremedaes.com" "quick question about your booking forms" "$MEDSPA_HTML"
send_email "concierge@nakedmd.com" "67% of your consultation leads are invisible" "$MEDSPA_HTML"
send_email "juviamedicalspa@gmail.com" "67% of your consultation leads are invisible" "$MEDSPA_HTML"
send_email "prestonroyal@skinspirit.com" "67% of your consultation leads are invisible" "$MEDSPA_HTML"
send_email "inwood@hiatusspa.com" "ReCapture x Hiatus — recovering invisible leads across 6 DFW locations" "$MEDSPA_HTML"

# Dental
send_email "howdy@rodeodental.com" "ReCapture x Rodeo Dental — 50+ locations, one blind spot" "$DENTAL_HTML"
send_email "info@mb2dental.com" "ReCapture x MB2 Dental — recovering invisible patient leads at scale" "$DENTAL_HTML"
send_email "feedback@myidealdental.com" "ReCapture x Ideal Dental — recovering invisible patient leads across 100+ locations" "$DENTAL_HTML"

# Plastic Surgery
send_email "info@drdeuber.com" "72% of consultation forms never make it to your team" "$SURGERY_HTML"
send_email "info@fwpsc.com" "72% of consultations never make it to your team" "$SURGERY_HTML"
send_email "info@drkevinhanz.com" "72% of your consultation forms go unfinished" "$SURGERY_HTML"

# Luxury Auto
send_email "social@avondale.com" "ReCapture x Avondale — recovering invisible buyer leads across 8 brands" "$AUTO_HTML"
send_email "jgriggs@ferraridallas.com" "thought of Ferrari Dallas when I saw this data" "$AUTO_HTML"

# Property Management
send_email "info@equityrem.com" "your leasing forms are losing prospects" "$PROPERTY_HTML"
send_email "contact@touchstonepm.com" "your leasing forms are losing prospects" "$PROPERTY_HTML"
send_email "info@olympusproperty.com" "ReCapture x Olympus — recovering invisible leasing leads across 130 communities" "$PROPERTY_HTML"
send_email "info@lpc.com" "ReCapture x Lincoln — recovering invisible leasing leads at enterprise scale" "$PROPERTY_HTML"
send_email "ssmith@pinnacleliving.com" "ReCapture x Pinnacle — recovering invisible leasing leads across 169,000 units" "$PROPERTY_HTML"

echo "================================"
echo "New batch complete."
