import subprocess, json, time

API_KEY = "re_FdNcsnxT_9ZA3oDGrQjsNcP73GaMw3DSN"

def send(to, subject, html):
    body = json.dumps({"from":"Ash from ReCapture <hello@userecapture.com>","to":to,"reply_to":"asherton.c@me.com","subject":subject,"html":html})
    r = subprocess.run(["curl","-s","-X","POST","https://api.resend.com/emails","-H",f"Authorization: Bearer {API_KEY}","-H","Content-Type: application/json","-d",body], capture_output=True, text=True)
    if '"id"' in r.stdout:
        print(f"SENT: {to} — {subject}")
    else:
        print(f"FAILED: {to} — {r.stdout}")
    time.sleep(2)

MEDSPA = '<div style="font-family:-apple-system,Segoe UI,sans-serif;max-width:560px;margin:0 auto;background:#0a0a0a;color:#ccc;padding:36px 32px;border-radius:10px"><div style="margin-bottom:28px"><span style="font-size:18px;font-weight:700;color:#fff">Re</span><span style="font-size:18px;font-weight:700;color:#ff6b35">Capture</span></div><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:20px">Hi there,</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:20px">I am Ash — I run a digital marketing consultancy here in the Harwood District in Dallas. I have spent the last 10+ years working with med spas and high-ticket service businesses, and I kept seeing the same problem everywhere.</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:20px">Between 60-70% of people who start a consultation form never finish it. They type their name, email, maybe their phone — then they get distracted and close the tab. Nobody shows you the people in between.</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:20px">For med spas, the average client is worth $2,800. Across multiple locations, those invisible leads add up to six figures in lost revenue every year.</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:24px">I built ReCapture to fix this. One script tag per location — 60 seconds to install. Every person who starts your form is captured in real time, even if they never hit submit. Enterprise dashboard across all your locations.</p><div style="text-align:center;margin:28px 0"><a href="https://www.userecapture.com/test-form" style="display:inline-block;background:#ff6b35;color:#fff;font-weight:700;padding:12px 28px;border-radius:8px;text-decoration:none;font-size:14px">See It in Action</a></div><p style="font-size:14px;line-height:1.7;color:#888;margin-bottom:20px">You can also <a href="https://www.userecapture.com/for-med-spas" style="color:#ff6b35;text-decoration:none">see how it works for med spas</a> or <a href="https://www.userecapture.com/calculator" style="color:#ff6b35;text-decoration:none">run a free ROI estimate</a>.</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:4px">Happy to walk you through it.</p><div style="margin-top:28px;padding-top:20px;border-top:1px solid #1e1e1e"><p style="margin:0;font-size:14px;font-weight:600;color:#fff">Asherton Chraibi</p><p style="margin:2px 0 0;font-size:13px;color:#666">Founder, ReCapture</p><p style="margin:2px 0 0;font-size:13px;color:#666">Dallas, TX</p><p style="margin:4px 0 0;font-size:13px"><a href="https://www.userecapture.com" style="color:#ff6b35;text-decoration:none">userecapture.com</a></p></div></div>'

ASPEN = '<div style="font-family:-apple-system,Segoe UI,sans-serif;max-width:560px;margin:0 auto;background:#0a0a0a;color:#ccc;padding:36px 32px;border-radius:10px"><div style="margin-bottom:28px"><span style="font-size:18px;font-weight:700;color:#fff">Re</span><span style="font-size:18px;font-weight:700;color:#ff6b35">Capture</span></div><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:20px">Hi there,</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:20px">I am Ash — I run a digital marketing consultancy here in Dallas. I work with dental groups in DFW and kept seeing the same blind spot across every practice.</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:20px">65% of people who start an appointment or new patient form never finish it. They type their name, maybe their insurance — then they close the tab and book with a competitor. The practice that captures those leads first wins the patient.</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:20px">In a market like DFW where Aspen, Ideal, and every other group is competing for the same patients — the difference between winning and losing is seeing the leads your competitors cannot.</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:24px">I built ReCapture to fix this. One script tag per location site — 60 seconds to install. Every person who starts your form is captured in real time, even if they never submit. Enterprise dashboard across all your locations.</p><div style="text-align:center;margin:28px 0"><a href="https://www.userecapture.com/test-form" style="display:inline-block;background:#ff6b35;color:#fff;font-weight:700;padding:12px 28px;border-radius:8px;text-decoration:none;font-size:14px">See It in Action</a></div><p style="font-size:14px;line-height:1.7;color:#888;margin-bottom:20px">You can also <a href="https://www.userecapture.com/for-dental" style="color:#ff6b35;text-decoration:none">see how it works for dental</a> or <a href="https://www.userecapture.com/calculator" style="color:#ff6b35;text-decoration:none">run a free ROI estimate</a>.</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:4px">Happy to walk you through it.</p><div style="margin-top:28px;padding-top:20px;border-top:1px solid #1e1e1e"><p style="margin:0;font-size:14px;font-weight:600;color:#fff">Asherton Chraibi</p><p style="margin:2px 0 0;font-size:13px;color:#666">Founder, ReCapture</p><p style="margin:2px 0 0;font-size:13px;color:#666">Dallas, TX</p><p style="margin:4px 0 0;font-size:13px"><a href="https://www.userecapture.com" style="color:#ff6b35;text-decoration:none">userecapture.com</a></p></div></div>'

DENTAL = '<div style="font-family:-apple-system,Segoe UI,sans-serif;max-width:560px;margin:0 auto;background:#0a0a0a;color:#ccc;padding:36px 32px;border-radius:10px"><div style="margin-bottom:28px"><span style="font-size:18px;font-weight:700;color:#fff">Re</span><span style="font-size:18px;font-weight:700;color:#ff6b35">Capture</span></div><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:20px">Hi there,</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:20px">I am Ash — I run a digital marketing consultancy here in Dallas. I work with dental groups across DFW and kept seeing the same problem at every practice.</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:20px">65% of people who start a patient intake or appointment form never finish it. They type their name, email, maybe insurance info — then they close the tab. Nobody shows you those people.</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:20px">A single new patient is worth $1,900 over their lifetime. Across hundreds of locations, that adds up to millions in invisible lost revenue per year.</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:24px">I built ReCapture to fix this. One script tag per location — 60 seconds to install. Every person who starts your form is captured in real time, even if they never submit. Enterprise dashboard across your entire network.</p><div style="text-align:center;margin:28px 0"><a href="https://www.userecapture.com/test-form" style="display:inline-block;background:#ff6b35;color:#fff;font-weight:700;padding:12px 28px;border-radius:8px;text-decoration:none;font-size:14px">See It in Action</a></div><p style="font-size:14px;line-height:1.7;color:#888;margin-bottom:20px">You can also <a href="https://www.userecapture.com/for-dental" style="color:#ff6b35;text-decoration:none">see how it works for dental</a> or <a href="https://www.userecapture.com/calculator" style="color:#ff6b35;text-decoration:none">run a free ROI estimate</a>.</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:4px">Happy to walk you through it.</p><div style="margin-top:28px;padding-top:20px;border-top:1px solid #1e1e1e"><p style="margin:0;font-size:14px;font-weight:600;color:#fff">Asherton Chraibi</p><p style="margin:2px 0 0;font-size:13px;color:#666">Founder, ReCapture</p><p style="margin:2px 0 0;font-size:13px;color:#666">Dallas, TX</p><p style="margin:4px 0 0;font-size:13px"><a href="https://www.userecapture.com" style="color:#ff6b35;text-decoration:none">userecapture.com</a></p></div></div>'

DERM = '<div style="font-family:-apple-system,Segoe UI,sans-serif;max-width:560px;margin:0 auto;background:#0a0a0a;color:#ccc;padding:36px 32px;border-radius:10px"><div style="margin-bottom:28px"><span style="font-size:18px;font-weight:700;color:#fff">Re</span><span style="font-size:18px;font-weight:700;color:#ff6b35">Capture</span></div><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:20px">Hi there,</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:20px">I am Ash — I run a digital marketing consultancy here in Dallas. I work with dermatology practices and multi-location medical groups, and I kept seeing the same blind spot everywhere.</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:20px">Between 60-70% of people who start an appointment request or patient intake form never finish it. They type their name, their concern, maybe their insurance — then they close the tab. Nobody shows you those people.</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:20px">For dermatology, each new patient represents $1,500-3,000 in lifetime value. Across your network, those invisible abandoned forms add up to millions in lost revenue per year.</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:24px">I built ReCapture to fix this. One script tag per location — 60 seconds to install. Every person who starts your form is captured in real time. Enterprise dashboard across all your offices.</p><div style="text-align:center;margin:28px 0"><a href="https://www.userecapture.com/test-form" style="display:inline-block;background:#ff6b35;color:#fff;font-weight:700;padding:12px 28px;border-radius:8px;text-decoration:none;font-size:14px">See It in Action</a></div><p style="font-size:14px;line-height:1.7;color:#888;margin-bottom:20px"><a href="https://www.userecapture.com/calculator" style="color:#ff6b35;text-decoration:none">Run a free ROI estimate</a> to see how much your forms might be costing you.</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:4px">Happy to walk you through it.</p><div style="margin-top:28px;padding-top:20px;border-top:1px solid #1e1e1e"><p style="margin:0;font-size:14px;font-weight:600;color:#fff">Asherton Chraibi</p><p style="margin:2px 0 0;font-size:13px;color:#666">Founder, ReCapture</p><p style="margin:2px 0 0;font-size:13px;color:#666">Dallas, TX</p><p style="margin:4px 0 0;font-size:13px"><a href="https://www.userecapture.com" style="color:#ff6b35;text-decoration:none">userecapture.com</a></p></div></div>'

PROP = '<div style="font-family:-apple-system,Segoe UI,sans-serif;max-width:560px;margin:0 auto;background:#0a0a0a;color:#ccc;padding:36px 32px;border-radius:10px"><div style="margin-bottom:28px"><span style="font-size:18px;font-weight:700;color:#fff">Re</span><span style="font-size:18px;font-weight:700;color:#ff6b35">Capture</span></div><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:20px">Hi there,</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:20px">I am Ash — I run a digital marketing consultancy here in the Harwood District in Dallas. I work with property management companies and multifamily operators across DFW.</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:20px">70% of people who start a leasing inquiry or tour request form never finish it. They type their name, the unit they want — then they move on to the next listing. Nobody shows you those people.</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:20px">Every abandoned inquiry is a $3,200+ annual lease walking away. Across your portfolio, that is millions in lost lease revenue per year.</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:24px">I built ReCapture to fix this. One script tag per property site — 60 seconds to install. Enterprise dashboard across all your communities.</p><div style="text-align:center;margin:28px 0"><a href="https://www.userecapture.com/test-form" style="display:inline-block;background:#ff6b35;color:#fff;font-weight:700;padding:12px 28px;border-radius:8px;text-decoration:none;font-size:14px">See It in Action</a></div><p style="font-size:14px;line-height:1.7;color:#888;margin-bottom:20px">You can also <a href="https://www.userecapture.com/for-property-management" style="color:#ff6b35;text-decoration:none">see how it works for property management</a> or <a href="https://www.userecapture.com/calculator" style="color:#ff6b35;text-decoration:none">run a free ROI estimate</a>.</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:4px">Happy to walk you through it.</p><div style="margin-top:28px;padding-top:20px;border-top:1px solid #1e1e1e"><p style="margin:0;font-size:14px;font-weight:600;color:#fff">Asherton Chraibi</p><p style="margin:2px 0 0;font-size:13px;color:#666">Founder, ReCapture</p><p style="margin:2px 0 0;font-size:13px;color:#666">Dallas, TX</p><p style="margin:4px 0 0;font-size:13px"><a href="https://www.userecapture.com" style="color:#ff6b35;text-decoration:none">userecapture.com</a></p></div></div>'

AUTO = '<div style="font-family:-apple-system,Segoe UI,sans-serif;max-width:560px;margin:0 auto;background:#0a0a0a;color:#ccc;padding:36px 32px;border-radius:10px"><div style="margin-bottom:28px"><span style="font-size:18px;font-weight:700;color:#fff">Re</span><span style="font-size:18px;font-weight:700;color:#ff6b35">Capture</span></div><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:20px">Hi there,</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:20px">I am Ash — I run a digital marketing consultancy here in Dallas. I thought of your dealership group when I came across some data I wanted to share.</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:20px">74% of people who start a vehicle inquiry form never finish it. They type their name, the model they want — then they close the tab. Nobody shows you those people.</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:20px">Across 13+ dealerships, even a 5% recovery rate on those invisible leads is hundreds of thousands in additional revenue per year.</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:24px">I built ReCapture to fix this. One script tag per dealership site — 60 seconds to install. Enterprise dashboard across your entire group.</p><div style="text-align:center;margin:28px 0"><a href="https://www.userecapture.com/test-form" style="display:inline-block;background:#ff6b35;color:#fff;font-weight:700;padding:12px 28px;border-radius:8px;text-decoration:none;font-size:14px">See It in Action</a></div><p style="font-size:14px;line-height:1.7;color:#888;margin-bottom:20px">You can also <a href="https://www.userecapture.com/for-luxury-auto" style="color:#ff6b35;text-decoration:none">see how it works for auto</a> or <a href="https://www.userecapture.com/calculator" style="color:#ff6b35;text-decoration:none">run a free ROI estimate</a>.</p><p style="font-size:15px;line-height:1.7;color:#bbb;margin-bottom:4px">Happy to walk you through it.</p><div style="margin-top:28px;padding-top:20px;border-top:1px solid #1e1e1e"><p style="margin:0;font-size:14px;font-weight:600;color:#fff">Asherton Chraibi</p><p style="margin:2px 0 0;font-size:13px;color:#666">Founder, ReCapture</p><p style="margin:2px 0 0;font-size:13px;color:#666">Dallas, TX</p><p style="margin:4px 0 0;font-size:13px"><a href="https://www.userecapture.com" style="color:#ff6b35;text-decoration:none">userecapture.com</a></p></div></div>'

contacts = [
    # Med Spa / Aesthetics
    ("info@injectco.com", "67% of your consultation leads are invisible — across 6 locations", MEDSPA),
    ("info@genesislifestylemedicine.com", "ReCapture x Genesis — recovering invisible leads across 30+ locations", MEDSPA),
    ("customerservice@laseraway.com", "ReCapture x LaserAway — recovering invisible leads at scale", MEDSPA),
    ("marissa@renownweightloss.com", "67% of your consultation leads are invisible", MEDSPA),
    # Dental — Aspen gets the competitive angle
    ("social@aspendental.com", "your biggest competitor is losing leads the same way — whoever fixes it first wins", ASPEN),
    ("info@pacificdentalservices.com", "ReCapture x PDS — recovering invisible patient leads across 900+ offices", DENTAL),
    ("info@heartland.com", "ReCapture x Heartland — recovering invisible patient leads across 1,700 locations", DENTAL),
    # Dermatology
    ("info@preferredderm.com", "ReCapture x Preferred Derm — recovering invisible patient leads across 12+ DFW offices", DERM),
    ("info@epiphanydermatology.com", "ReCapture x Epiphany — recovering invisible patient leads across 75+ locations", DERM),
    # Property Management
    ("julie.ellison@greystar.com", "ReCapture x Greystar DFW — recovering invisible leasing leads across your portfolio", PROP),
    ("info@jpi.com", "ReCapture x JPI — recovering invisible leasing leads across Jefferson communities", PROP),
    ("info@allresco.com", "ReCapture x Alliance — recovering invisible leasing leads across Broadstone DFW", PROP),
    # Luxury Auto
    ("customerrelations@autonation.com", "ReCapture x AutoNation — recovering invisible buyer leads across DFW", AUTO),
    # Weight Loss
    ("info@freshimagecenter.com", "67% of your consultation leads are invisible", MEDSPA),
    ("info@vitalyc.com", "ReCapture x Vitalyc — recovering invisible leads across 6 DFW locations", MEDSPA),
]

print(f"Starting WAVE 3 — {len(contacts)} emails")
print("=" * 50)
for to, subj, html in contacts:
    send(to, subj, html)
print("=" * 50)
print("Wave 3 complete.")
